version: "3"
services:
  database:
    build: ./db/
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USERr=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=tutowebdb    
    ports:
      - "3306:3306"
  api:
    build: ./api/
    depends_on:
      - database
    environment:
      - PORT = 3006
      - DB_HOST = database  
      - DB_PORT = 3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_DATABASE=tutowebdb
    ports:
      - "3006:3006"
  front:
    build: ./front/
    depends_on:
      - api
    ports:
      - "80:80"
