version: "3"
services:
  database:
    build: ./db/
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3307:3307"
  api:
    build: ./api/
    depends_on:
      - database
    ports:
      - "3006:3006"
  front:
    build: ./front/
    depends_on:
      - api
    ports:
      - "80:80"
