version: "3"
services:
  database:
    build: ./db/
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USERr=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=pre_interia    
    ports:
      - "3306:3306"
  api:
    build: ./api/
    depends_on:
      - database
    ports:
      - "3006:3006"
  front:
    build: ./front/
    depends_on:
      - api
    ports:
      - "80:80"
